name: Build

on:
  push:
    branches:
    - master
    tags:
    - '*'

    paths-ignore:
    - "docs/**"
    - ".github/**"

jobs:
  build:
    strategy:
      matrix:
        type: [retail, wrath, classic, cata]
        include:
          - type: retail
            pkgmeta: .pkgmeta
          - type: wrath
            pkgmeta: .pkgmeta_wrath
          - type: cata
            pkgmeta: .pkgmeta_cata
          - type: classic
            pkgmeta: .pkgmeta_vanilla

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
